In [1]:
import numpy as np

In [2]:
n = 10
P = np.abs(np.random.standard_normal((n,n)))
P = P/P.sum(axis=0)
# eig <= 1

In [3]:
u, s, vt = np.linalg.svd(P)
s

array([1.01005746, 0.43543193, 0.3719264 , 0.30972128, 0.28689935,
       0.22216912, 0.20360059, 0.16879595, 0.06406778, 0.02268558])

In [4]:
u, s, vt = np.linalg.svd(0.9*P)
s

array([0.90905171, 0.39188874, 0.33473376, 0.27874915, 0.25820942,
       0.19995221, 0.18324053, 0.15191636, 0.05766101, 0.02041702])

In [5]:
_, s, _ = np.linalg.svd(u)
s

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [6]:
np.linalg.solve(np.eye(n) - P, np.zeros(n))

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0., -0., -0.])

In [7]:
# s = Ps
# s - Ps = 0
# (I - P)s = 0

In [13]:
s = np.random.random(n)
s = s / s.sum()

In [23]:
def state_visitation_distribution(M_pi, discount, d_0, P):
    # Ps + yPPs + yyPPPs + yyyPPPPs ...
    # (P + yPP + yyPPP + yyyPPPP ... )s
    # (I - yP)^-1 s
    
    n = d_0.size
    P_pi = np.dot(M_pi, P)
    
    # check we have been given normalised distributions
    assert np.isclose(d_0/d_0.sum(), d_0).all()
    assert np.isclose(P_pi/P_pi.sum(0), P_pi).all()
    
    return (1-discount)*np.dot(np.linalg.inv(np.eye(n) - discount * P_pi), d_0)

In [24]:
def entropy(d):
    b = d.size
    return - np.sum(d * np.log(d) / np.log(b)) 

def max_entropy_exploration(ds_0t):
    g = dH(ds_0t, M_pi)
    return M_pi - lr * g

In [ ]:
def count_based_exploration(ds_0t, P):
    # pick a policy that chooses actions
    # with high probabilty if they have not been visited frequently
    # P(s' | s, a) . (1-d(s'))
    return np.einsum(P, (1-ds_0t), 'ijk,i->jk')

In [ ]:
def udb_exploration(ds_0t):
    # the confidence in what!?
    return 

In [15]:
d_empirical = (1-0.9)*sum([np.dot((0.9**(i-1))*np.linalg.matrix_power(P, i), s) 
                   for i in range(1, 100000)])
d_empirical

array([0.08550294, 0.09573569, 0.11021839, 0.12092368, 0.08210548,
       0.0834563 , 0.11916286, 0.10651392, 0.08473119, 0.11164954])

In [16]:
d_analytic - d_empirical

array([-0.00182639, -0.00077783, -0.00948273, -0.00204928, -0.00200989,
       -0.00234924, -0.00030575,  0.00174053,  0.01509885,  0.00196174])

In [19]:
d_analytic

array([0.08367655, 0.09495786, 0.10073565, 0.1188744 , 0.08009559,
       0.08110706, 0.11885711, 0.10825445, 0.09983004, 0.11361129])